version: "3.8"

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 80
        environment: 
            VIRTUAL_HOST: audiopirtis.lt, www.audiopirtis.lt

networks:
  default:
    external:
      name: nginx-proxy
        